services:
  mysql:
    image: mysql:8.0.43
    container_name: spring-boot
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: englishdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: